[[section-introduction-and-goals]]
== Introduction and Goals
The aim of the project is to develop a decentralised route tracker, which has to be able to give an excellent performance meanwhile the privacy of the customer is well kept.
[role="arc42help"]
****
Initial commit
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview
According to the priority of each requirement, we can order them as you can read next.

* The application must implement a decentralised architecture based in the SoLiD (Social Linked Data) specifications, therefore stored data must be separated from the app.
* Information must be stored in pods.
* Routes will be shown to users on the map.
* A route should be fed back with relative data, such as shared pictures, videos or comments.
* Notifications will be sent as a result of a friend sharing a route.
* There can exist user groups for multiple sharing purposes.
* Interoperability is an essential part of our specific application, so several apps are able to work with the same information of a route.

=== Quality Goals
* Availability. The application should be a consistent.
* Privacy. As a SoLiD project, keeping the personal data is a main quality purpose.
* Usability. The app must be easy to use, all sort of users should know how to use all the features.

=== Stakeholders

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Teacher | labra@uniovi.es | They will evaluate our project 
| Solid community | https://solid.mit.edu | Resource for the Solid project
| Developers | https://github.com/Arquisoft/viade_es2c | They will develop the architecture and the code of the application
|Users | | People that want to keep track of their routes and their privacy
|===
