[[section-introduction-and-goals]]
== Introduction and Goals
The aim of the project is to develop a decentralised route tracker, which has to be able to give an excellent performance meanwhile the privacy of the customer is well kept.

=== Requirements Overview
According to the priority of each requirement, we can order them as you can read next.

* The application must implement a decentralised architecture based in the SOLID (Social Linked Data) specifications, therefore stored data must be separated from the app.
* Information must be stored in pods.
* Routes will be shown to users on the map.
* A route should be fed back with relative data, such as shared pictures, videos or comments.
* Notifications will be sent as a result of a friend sharing a route.
* There can exist user groups for multiple sharing purposes.
* Interoperability is an essential part of our specific application, so several apps are able to work with the same information of a route.

=== Quality Goals
* Consistency. The application should be a consistent.
* Privacy. As a SOLID project, keeping the personal data is a main quality purpose.
* Usability. The app must be easy to use, at least the average user should be able to interact easily with viade.
* Interoperability with other Viade apps that our classmates are creating.

=== Stakeholders

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Teacher | https://github.com/labra | He will evaluate our project 
| Solid community | https://solid.mit.edu | Resource for the Solid project
| Developers | https://github.com/Arquisoft/viade_es2c | They will develop the architecture and the code of the application
|Technical Users | | People that have some experience in the route's world and know some technical concepts
|Non-technical users | People that is new in the world and have never used a route's management app before
| Disables users | Users who have some kind of disability
|Users without an account | People new in the SOLID or Inrupt community and want touse our app
|Users with an account | User's from SOLID or Inrupt who want to use our app
|===
