[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Log in
The login process will be done by users when they log in with their pesonal id to access the application.

1. The user click login button.
2. The user enters his credentials.
3. Their data is sent to a LoginManager to try to log in.
4. The server can deny or approve the authentication.
5. The user can start using the application's features.

[plantuml,"Log in secuence diagram",png]
----
User -> Viade: 1. login request
Viade -> LoginManager: 2. user credentials
LoginManager -> Server: 3. log in try
Server -> Viade: 4. authentication approved
Server -> LoginManager: 4. authentication denied
User -> Viade: 5. routes management
----
=== Routes Management
The users use the application to manage their routes.

1. The user creates a new route.
2. The user shares a route to a friend or a group of friends.

[plantuml,"Routes creation secuence diagram",png]
----
title User creates a new route
actor User1
participant Viade1
database POD
User1 -> Viade1: 1. create new route
Viade1 -> POD: saves the route

----

[plantuml,"Routes share 1 secuence diagram",png]
----
title User shares route to a friend
actor User1
participant Viade1
database POD
participant Viade2
actor User2
User1 -> Viade1: 1. create new route
Viade1 -> POD: saves the route
User1 -> Viade1: 2. shares route
Viade1 -> POD: allows to see the route
Viade2 -> POD: access route
Viade2 -> User2: show route
----

[plantuml,"Routes share 2 secuence diagram",png]
----
title User shares route to a group of friends
actor User1
participant Viade1
database POD
participant ViadeX
collections User_group
User1 -> Viade1: 1. create new route
Viade1 -> POD: saves the route
User1 -> Viade1: 2. shares route
Viade1 -> POD: allows to see the route
ViadeX -> POD: recieve route
ViadeX -> User_group: show route
----
