[[section-technical-risks]]
== Risks and Technical Debts


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****
At this moment, we don't have any technical debt (this is our first deadline and we only have to write some documentation) but we do have risks:

[options="header",cols="1,2,2,2"]
|===
|Priority|Risk |Consequence | Possible Solution
| 1|Not being used to the technology | Be slow at developing or make mistakes and waste time | Reading and learning about React, SOLID and RDF. We should do some tutorials and use the SOLID forum and gitter.
|2| First time forming a team| We don't know how to work with each other so we may not understand each other and consume time or be uncomfortable | Communication and interest
|3|  Not having much time | We only have 3 months to create this app and just have the course hours and some free time that we need to organize with other subjects | Organization
|===